vars:
  - params.json

stages:
  fetch_data_pol_plan_subj_call:
    cmd: >-
      python3 ${dvc_root}${scripts.fetch_data}
      -i "${dvc_root}${data.raw_data.pol.plan_subj_call}"
      -o "${dvc_root}${data.interim_data.pol.plan_subj_call}"
    deps:
      - ${dvc_root}${data.raw_data.pol.plan_subj_call}
    outs:
      - ${dvc_root}${data.interim_data.pol.plan_subj_call}
    wdir: ${dvc_root}${wdir.fetch_data}
  fetch_data_pol_scholarship_per_year:
    cmd: >-
      python3 ${dvc_root}${scripts.fetch_data}
      -i "${dvc_root}${data.raw_data.pol.scholarship}"
      -o "${dvc_root}${data.interim_data.pol.scholarship}"
    deps:
      - ${dvc_root}${data.raw_data.pol.scholarship}
    outs:
      - ${dvc_root}${data.interim_data.pol.scholarship}
    wdir: ${dvc_root}${wdir.fetch_data}
  fetch_data_pol_personal_access:
    cmd: >-
      python3 ${dvc_root}${scripts.fetch_data}
      -i "${dvc_root}${data.raw_data.pol.personal_access}"
      -o "${dvc_root}${data.interim_data.pol.personal_access}"
    deps:
      - ${dvc_root}${data.raw_data.pol.personal_access}
    outs:
      - ${dvc_root}${data.interim_data.pol.personal_access}
    wdir: ${dvc_root}${wdir.fetch_data}
  etl_pol_plan_subj_call:
    cmd: >-
      python3 ${dvc_root}${scripts.etl.scolarship_per_year_&_plan_subj_call}
      -i "${dvc_root}${data.interim_data.pol.plan_subj_call}"
      -o "${dvc_root}${data.processed_data.pol.plan_subj_call}"
      -s "${school_kind.pol}"
    deps:
      - ${dvc_root}${data.interim_data.pol.plan_subj_call}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
    wdir: ${dvc_root}${wdir.etl.scolarship_per_year_&_plan_subj_call}
  etl_pol_scolarship_per_year:
    cmd: >-
      python3 ${dvc_root}${scripts.etl.scolarship_per_year_&_plan_subj_call}
      -i "${dvc_root}${data.interim_data.pol.scholarship}"
      -o "${dvc_root}${data.processed_data.pol.scholarship}"
      -s "${school_kind.pol}"
    deps:
      - ${dvc_root}${data.interim_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.processed_data.pol.scholarship}
    wdir: ${dvc_root}${wdir.etl.scolarship_per_year_&_plan_subj_call}
  etl_pol_record_personal_access:
    cmd: >-
      python3 ${dvc_root}${scripts.etl.record_personal_access}
      -i "${dvc_root}${data.interim_data.pol.personal_access}" "${dvc_root}${data.processed_data.pol.plan_subj_call}"
      -o "${dvc_root}${data.processed_data.pol.personal_access}"
      -s "${school_kind.pol}"
    deps:
      - ${dvc_root}${data.interim_data.pol.personal_access}
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.processed_data.pol.personal_access}
    wdir: ${dvc_root}${wdir.etl.record_personal_access}
  feat_eng_pol_personal_access:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.personal_access_script}
      -i "${dvc_root}${data.processed_data.pol.personal_access}"
      -o "${dvc_root}${data.analys_data.personal_access_data.pol}"
      -s "${school_kind.pol}"
    deps:
      - ${dvc_root}${data.processed_data.pol.personal_access}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.personal_access_data.pol}
    wdir: ${dvc_root}${wdir.feat_eng.personal_access_script}
  feat_sel_pol_personal_access:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.personal_access_data.pol}"
      -o "${dvc_root}${data.final_analys_data.personal_access_data.pol}"
      -s "${school_kind.pol}"
      -c 0
      -q 0
    deps:
      - ${dvc_root}${data.analys_data.personal_access_data.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.personal_access_data.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
  analysis_pol_personal_access:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.personal_access_data.pol}"
      -o "${dvc_root}${data.pred_analys_data.personal_access_data.pol}"
      -s "${school_kind.pol}"
      -c 0
      -q 0
      -mn "1st_model"
    deps:
      - ${dvc_root}${data.final_analys_data.personal_access_data.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.personal_access_data.pol}
    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_1st_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.pred_analys_data.personal_access_data.pol}" "${dvc_root}${data.processed_data.pol.plan_subj_call}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.1st_quad.pol}"
      -s "${school_kind.pol}"
      -c 1
      -q 1
    deps:
      - ${dvc_root}${data.pred_analys_data.personal_access_data.pol}
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.1st_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_1st_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.1st_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.1st_quad.pol}"
      -s "${school_kind.pol}"
      -c 1
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.1st_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.1st_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
  analys_pol_1st_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.1st_quad.pol}"
      -o "${dvc_root}${data.pred_analys_data.1st_quad.pol}"
      -s "${school_kind.pol}"
      -c 1
      -q 1
      -mn "1st_model"
    deps:
      - ${dvc_root}${data.final_analys_data.1st_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.1st_quad.pol}
    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_2nd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.pred_analys_data.1st_quad.pol}" "${dvc_root}${data.processed_data.pol.plan_subj_call}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.2nd_quad.pol}"
      -s "${school_kind.pol}"
      -c 1
      -q 2
    deps:
      - ${dvc_root}${data.pred_analys_data.1st_quad.pol}
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.2nd_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_2nd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.2nd_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.2nd_quad.pol}"
      -s "${school_kind.pol}"
      -c 1
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.2nd_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.2nd_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
  analys_pol_2nd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.2nd_quad.pol}"
      -o "${dvc_root}${data.pred_analys_data.2nd_quad.pol}"
      -s "${school_kind.pol}"
      -c 1
      -q 2
      -mn "2nd_model"
    deps:
      - ${dvc_root}${data.final_analys_data.2nd_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.2nd_quad.pol}
    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_3rd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.pred_analys_data.2nd_quad.pol}" "${dvc_root}${data.processed_data.pol.plan_subj_call}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.3rd_quad.pol}"
      -s "${school_kind.pol}"
      -c 2
      -q 1
    deps:
      - ${dvc_root}${data.pred_analys_data.2nd_quad.pol}
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.3rd_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_3rd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.3rd_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.3rd_quad.pol}"
      -s "${school_kind.pol}"
      -c 2
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.3rd_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.3rd_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
  analys_pol_3rd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.3rd_quad.pol}"
      -o "${dvc_root}${data.pred_analys_data.3rd_quad.pol}"
      -s "${school_kind.pol}"
      -c 2
      -q 1
      -mn "3rd_model"
    deps:
      - ${dvc_root}${data.final_analys_data.3rd_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.3rd_quad.pol}
    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_4th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.pred_analys_data.3rd_quad.pol}" "${dvc_root}${data.processed_data.pol.plan_subj_call}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.4th_quad.pol}"
      -s "${school_kind.pol}"
      -c 2
      -q 2
    deps:
      - ${dvc_root}${data.pred_analys_data.3rd_quad.pol}
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.4th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_4th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.4th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.4th_quad.pol}"
      -s "${school_kind.pol}"
      -c 2
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.4th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.4th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
  analys_pol_4th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.4th_quad.pol}"
      -o "${dvc_root}${data.pred_analys_data.4th_quad.pol}"
      -s "${school_kind.pol}"
      -c 2
      -q 2
      -mn "4th_model"
    deps:
      - ${dvc_root}${data.final_analys_data.4th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.4th_quad.pol}
    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_5th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.pred_analys_data.4th_quad.pol}" "${dvc_root}${data.processed_data.pol.plan_subj_call}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.5th_quad.pol}"
      -s "${school_kind.pol}"
      -c 3
      -q 1
    deps:
      - ${dvc_root}${data.pred_analys_data.4th_quad.pol}
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.5th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_5th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.5th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.5th_quad.pol}"
      -s "${school_kind.pol}"
      -c 3
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.5th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.5th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
  analys_pol_5th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.5th_quad.pol}"
      -o "${dvc_root}${data.pred_analys_data.5th_quad.pol}"
      -s "${school_kind.pol}"
      -c 3
      -q 1
      -mn "5th_model"
    deps:
      - ${dvc_root}${data.final_analys_data.5th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.5th_quad.pol}
    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_6th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.pred_analys_data.5th_quad.pol}" "${dvc_root}${data.processed_data.pol.plan_subj_call}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.6th_quad.pol}"
      -s "${school_kind.pol}"
      -c 3
      -q 2
    deps:
      - ${dvc_root}${data.pred_analys_data.5th_quad.pol}
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.6th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_6th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.6th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.6th_quad.pol}"
      -s "${school_kind.pol}"
      -c 3
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.6th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.6th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
  analys_pol_6th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.6th_quad.pol}"
      -o "${dvc_root}${data.pred_analys_data.6th_quad.pol}"
      -s "${school_kind.pol}"
      -c 3
      -q 2
      -mn "6th_model"
    deps:
      - ${dvc_root}${data.final_analys_data.6th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.6th_quad.pol}
    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_7th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.pred_analys_data.6th_quad.pol}" "${dvc_root}${data.processed_data.pol.plan_subj_call}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.7th_quad.pol}"
      -s "${school_kind.pol}"
      -c 4
      -q 1
    deps:
      - ${dvc_root}${data.pred_analys_data.6th_quad.pol}
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.7th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_7th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.7th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.7th_quad.pol}"
      -s "${school_kind.pol}"
      -c 4
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.7th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.7th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
  analys_pol_7th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.7th_quad.pol}"
      -o "${dvc_root}${data.pred_analys_data.7th_quad.pol}"
      -s "${school_kind.pol}"
      -c 4
      -q 1
      -mn "7th_model"
    deps:
      - ${dvc_root}${data.final_analys_data.7th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.7th_quad.pol}
    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_8th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.pred_analys_data.7th_quad.pol}" "${dvc_root}${data.processed_data.pol.plan_subj_call}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.8th_quad.pol}"
      -s "${school_kind.pol}"
      -c 4
      -q 2
    deps:
      - ${dvc_root}${data.pred_analys_data.7th_quad.pol}
      - ${dvc_root}${data.processed_data.pol.plan_subj_call}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.8th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_8th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.8th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.8th_quad.pol}"
      -s "${school_kind.pol}"
      -c 4
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.8th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.8th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
  analys_pol_8th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.8th_quad.pol}"
      -o "${dvc_root}${data.pred_analys_data.8th_quad.pol}"
      -s "${school_kind.pol}"
      -c 4
      -q 2
      -mn "8th_model"
    deps:
      - ${dvc_root}${data.final_analys_data.8th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.8th_quad.pol}
    wdir: ${dvc_root}${wdir.analys}
