vars:
  - params.json

stages:
  fetch_data_pol_personal_access:
    cmd: >-
      python3 ${dvc_root}${scripts.fetch_data}
      -i "${dvc_root}${data.raw_data.pol.personal_access}"
      -o "${dvc_root}${data.processed_data.pol.personal_access}"
      -s "${school_kind.pol}"
    deps:
      - ${dvc_root}${data.raw_data.pol.personal_access}
    outs:
      - ${dvc_root}${data.processed_data.pol.personal_access}
    wdir: ${dvc_root}${wdir.fetch_data}
  feat_eng_pol_personal_access:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.personal_access_script}
      -i "${dvc_root}${data.processed_data.pol.personal_access}"
      -o "${dvc_root}${data.dv_analys_data.personal_access_data.pol}"
      -s "${school_kind.pol}"
    deps:
      - ${dvc_root}${data.processed_data.pol.personal_access}
    outs:
      - ${dvc_root}${data.dv_analys_data.personal_access_data.pol}
    wdir: ${dvc_root}${wdir.feat_eng}
  analysis_before_pred_pol_personal_access:
    cmd: >-
      python3 ${dvc_root}${scripts.analys_before_pred}
      -i "${dvc_root}${data.final_analys_data.personal_access_data.pol}" "${dvc_root}${data.dv_analys_data.personal_access_data.pol}"
      -o "${dvc_root}${dir.dv_personal_access}"
      -s "${school_kind.pol}"
      -c 0
      -q 0
      -mn 0
    deps:
      - ${dvc_root}${data.final_analys_data.personal_access_data.pol}
      - ${dvc_root}${data.dv_analys_data.personal_access_data.pol}
    outs:
      - ${dvc_root}${models_developed.personal_access.gb}
      - ${dvc_root}${models_developed.personal_access.rf}
      - ${dvc_root}${models_developed.personal_access.svm}
    wdir: ${dvc_root}${wdir.analys}
  analysis_pol_personal_access:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.dv_analys_data.personal_access_data.pol}" "${dvc_root}${data.final_analys_data.personal_access_data.pol}"
      -o "${dvc_root}${data.pred_analys_data.personal_access_data.pol}"
      -im "${dvc_root}${models_developed.personal_access.gb}" "${dvc_root}${models_developed.personal_access.rf}" "${dvc_root}${models_developed.personal_access.svm}"
      -s "${school_kind.pol}"
      -c 0
      -q 0
      -mn 0
    deps:
      - ${dvc_root}${data.final_analys_data.personal_access_data.pol}
      - ${dvc_root}${data.dv_analys_data.personal_access_data.pol}
      - ${dvc_root}${models_developed.personal_access.gb}
      - ${dvc_root}${models_developed.personal_access.rf}
      - ${dvc_root}${models_developed.personal_access.svm}
    outs:
      - ${dvc_root}${data.pred_analys_data.personal_access_data.pol}
    wdir: ${dvc_root}${wdir.analys}