vars:
  - params.json

stages:
  analys_pol_1st_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.analys}
      -i "${dvc_root}${data.final_analys_data.1st_quad.pol}"
      -o "${dvc_root}${data.pred_analys_data.1st_quad.pol}"
      -s "${school_kind.pol}"
      -c 1
      -q 1
      -mn "${model.2nd_model}"
    deps:
      - ${dvc_root}${data.final_analys_data.1st_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.pred_analys_data.1st_quad.pol}
    wdir: ${dvc_root}${wdir.analys}
