wdir:
  analys: "/Code/Analysis_and_Modeling/"
scripts:
  analys: "/Code/Analysis_and_Modeling/ensemble_model.py"
school_kind:
  pol: "Polytechnic"
model:
  2nd_model: "2nd_model"
data:
    final_analys_data:
     1st_quad:
       pol: "/Data/For_Analysis_and_Modeling/1st_quadrimester/final_analys_polytechnic_record_personal_access.csv"
    pred_analys_data:
      1st_quad:
         pol: "/Data/For_Analysis_and_Modeling/1st_quadrimester/pred_analys_polytechnic_record_personal_access.csv"

