wdir:
  fetch_data: "/Code/Data_Visualization/Data_Acquisition"
  feat_eng: "/Code/Data_Visualization/Analysis_and_Modeling/Feature_Engineering/"
  analys: "/Code/Data_Visualization/Analysis_and_Modeling/Prediction"
dir:
  dv_personal_access: "/Data/Data_Visualization/record_personal_access/"
scripts:
  fetch_data: "/Code/Data_Visualization/Data_Acquisition/dv_data_acquisition.py"
  feat_eng:
    personal_access_script: "/Code/Data_Visualization/Analysis_and_Modeling/Feature_Engineering/dv_personal_access_feat_eng.py"
    quadrimesters_script: "/Code/Data_Visualization/Analysis_and_Modeling/Feature_Engineering/quadrimesters_feat_eng.py"
  analys_before_pred: "/Code/Data_Visualization/Analysis_and_Modeling/Prediction/ensemble_model_before_predict.py"
  analys: "/Code/Data_Visualization/Analysis_and_Modeling/Prediction/dv_prediction.py"
school_kind:
  pol: "Polytechnic"
models_developed:
  personal_access:
    gb: "/Data/Data_Visualization/record_personal_access/models/Polytechnic_gradientBoosting_model.sav"
    rf: "/Data/Data_Visualization/record_personal_access/models/Polytechnic_randomForest_model.sav"
    svm: "/Data/Data_Visualization/record_personal_access/models/Polytechnic_SVM_model.sav"
model:
  1: "1st_model"
  2: "2nd_model"
  3: "3rd_model"
  4: "4th_model"
  5: "5th_model"
  6: "6th_model"
  7: "7th_model"
  8: "8th_model"
data:
    raw_data:
      pol:
        personal_access: "/Data/Raw/Politecnica -datos de expediente,personales y de acceso.xls"
    processed_data:
       pol:
         plan_subj_call: "/Data/Processed/Polytechnic/Plan_Subject_Call/pr_polytechnic_plan_subject_call.csv"
         scholarship: "/Data/Processed/Polytechnic/Scolarship_per_year/pr_polytechnic_scholarship_per_year.csv"
         personal_access: "/Data/Processed/Polytechnic/Record_Personal_Access/pr_polytechnic_record_personal_access.csv"
    train_ids:
      personal_access_data: "/Data/Data_Visualization/record_personal_access/train_ids/Polytechnic_train_ids.csv"
    dv_analys_data:
     personal_access_data:
       pol: "/Data/Data_Visualization/record_personal_access/dv_analys_pol_record_personal_access.csv"
     1st_quad:
       pol: "/Data/Data_Visualization/1st_quad/dv_analys_pol.csv"
    final_analys_data:
     personal_access_data:
       pol: "/Data/For_Analysis_and_Modeling/personal_access_data/final_analys_polytechnic_record_personal_access.csv"
       teach: "/Data/For_Analysis_and_Modeling/personal_access_data/final_analys_teaching_record_personal_access.csv"
     1st_quad:
       pol: "/Data/For_Analysis_and_Modeling/1st_quadrimester/final_analys_polytechnic_record_personal_access.csv"
       teach: "/Data/For_Analysis_and_Modeling/1st_quadrimester/final_analys_teaching_record_personal_access.csv"
     2nd_quad:
       pol: "/Data/For_Analysis_and_Modeling/2nd_quadrimester/final_analys_polytechnic_record_personal_access.csv"
       teach: "/Data/For_Analysis_and_Modeling/2nd_quadrimester/final_analys_teaching_record_personal_access.csv"
     3rd_quad:
       pol: "/Data/For_Analysis_and_Modeling/3rd_quadrimester/final_analys_polytechnic_record_personal_access.csv"
       teach: "/Data/For_Analysis_and_Modeling/3rd_quadrimester/final_analys_teaching_record_personal_access.csv"
     4th_quad:
       pol: "/Data/For_Analysis_and_Modeling/4th_quadrimester/final_analys_polytechnic_record_personal_access.csv"
       teach: "/Data/For_Analysis_and_Modeling/4th_quadrimester/final_analys_teaching_record_personal_access.csv"
     5th_quad:
       pol: "/Data/For_Analysis_and_Modeling/5th_quadrimester/final_analys_polytechnic_record_personal_access.csv"
       teach: "/Data/For_Analysis_and_Modeling/5th_quadrimester/final_analys_teaching_record_personal_access.csv"
     6th_quad:
       pol: "/Data/For_Analysis_and_Modeling/6th_quadrimester/final_analys_polytechnic_record_personal_access.csv"
       teach: "/Data/For_Analysis_and_Modeling/6th_quadrimester/final_analys_teaching_record_personal_access.csv"
     7th_quad:
       pol: "/Data/For_Analysis_and_Modeling/7th_quadrimester/final_analys_polytechnic_record_personal_access.csv"
       teach: "/Data/For_Analysis_and_Modeling/7th_quadrimester/final_analys_teaching_record_personal_access.csv"
     8th_quad:
       pol: "/Data/For_Analysis_and_Modeling/8th_quadrimester/final_analys_polytechnic_record_personal_access.csv"
       teach: "/Data/For_Analysis_and_Modeling/8th_quadrimester/final_analys_teaching_record_personal_access.csv"
    pred_analys_data:
      personal_access_data:
        pol: "/Data/Data_Visualization/record_personal_access/dv_pred_pol_record_personal_access.csv"
      1st_quad:
         pol: "/Data/For_Analysis_and_Modeling/1st_quadrimester/pred_analys_polytechnic_record_personal_access.csv"
      2nd_quad:
         pol: "/Data/For_Analysis_and_Modeling/2nd_quadrimester/pred_analys_polytechnic_record_personal_access.csv"
      3rd_quad:
          pol: "/Data/For_Analysis_and_Modeling/3rd_quadrimester/pred_analys_polytechnic_record_personal_access.csv"
      4th_quad:
          pol: "/Data/For_Analysis_and_Modeling/4th_quadrimester/pred_analys_polytechnic_record_personal_access.csv"
      5th_quad:
          pol: "/Data/For_Analysis_and_Modeling/5th_quadrimester/pred_analys_polytechnic_record_personal_access.csv"
      6th_quad:
          pol: "/Data/For_Analysis_and_Modeling/6th_quadrimester/pred_analys_polytechnic_record_personal_access.csv"
      7th_quad:
          pol: "/Data/For_Analysis_and_Modeling/7th_quadrimester/pred_analys_polytechnic_record_personal_access.csv"
      8th_quad:
           pol: "/Data/For_Analysis_and_Modeling/8th_quadrimester/pred_analys_polytechnic_record_personal_access.csv"
