- name: Fix v cursor handling
  lineinfile:
    create: yes
    path: /home/ansible/.vimrc
    line: set nocompatible

- name: Add aliases to Bash
  blockinfile:
    create: yes
    path: /home/ansible/.bashrc
    block: |
      alias nano="nano -w"
      alias dir="ls -las -k -h -G"
      alias mv="mv -i"
      alias cp="cp -i"
      alias rm="rm -i"
      alias usage="du -h -d 1"

- name: Set US English locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set Timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid

- name: Enable UFW and Deny Everything
  ufw:
    state: enabled
    policy: deny

- name: Set UFW Logging On
  ufw:
    logging: "on"

- name: Allow SSH through UFW
  ufw:
    rule: allow
    name: OpenSSH

- name: Set UFW to Protect against SSH brute-force attacks
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Add DVC to the list of sources
  get_url:
    url: https://dvc.org/deb/dvc.list
    dest: /etc/apt/sources.list.d/dvc.list

- name: Update APT Cache
  apt:
    update_cache: yes
    upgrade: dist

- name: Install screen
  apt:
    name: screen
    state: latest

- name: Install pip
  apt:
    name: python3-pip
    state: latest

- name: Install DVC
  apt:
    name: dvc
    state: latest

- name: Copy project to Desktop
  ansible.builtin.copy:
    src: ../../../../../../education_drop
    dest: /home/{{ user }}/Desktop
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "644"

- name: Install desktop
  apt:
    name: ubuntu-desktop
    state: latest

- name: Reboot into desktop
  reboot:
