all:
  hosts:
    local:
      ansible_host: localhost
      ansible_port: 2222
      user: vagrant
      # https_port: 8443
      # mysql_root_password: caise
      # mysql_nextcloud_password: caise
      # nextcloud_admin_password: caise
    # remote:
    #   ansible_host: aaa.bbb.ccc.ddd
    #   ansible_port: 22
    #   user: caise
    #   https_port: 443
    #   mysql_root_password: XXXXXXXXXXXXXXXX
    #   mysql_nextcloud_password: XXXXXXXXXXXXXXXX
    #   nextcloud_admin_password: XXXXXXXXXXXXXXXX
